import { jsPDF } from 'jspdf';
import { Shipment, Vehicle, Incident, RoadSegment } from '../types';

export function generateLogisticsReport(
  reportTitle: string,
  stateFilter: string,
  shipments: Shipment[],
  vehicles: Vehicle[],
  incidents: Incident[],
  roads: RoadSegment[]
) {
  const doc = new jsPDF();
  const dateStr = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  // Header styling
  doc.setFillColor(8, 127, 140); // Soft Teal
  doc.rect(0, 0, 210, 30, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('PRAVAHA', 14, 18);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Logistics & Accessibility Intelligence Platform', 14, 25);
  doc.text(dateStr, 130, 25);

  let y = 42;

  // Title
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(reportTitle.toUpperCase(), 14, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Region Scope: ${stateFilter}`, 14, y);
  doc.text(`Generated by: Arjun Mehta (Logistics Administrator)`, 110, y);
  y += 12;

  // Executive Summary Box
  doc.setFillColor(241, 245, 247);
  doc.rect(14, y, 182, 26, 'F');
  doc.setDrawColor(226, 232, 240);
  doc.rect(14, y, 182, 26, 'S');

  doc.setFont('helvetica', 'bold');
  doc.text('EXECUTIVE SUMMARY', 18, y + 7);

  doc.setFont('helvetica', 'normal');
  const summaryText = `Active Shipments: ${shipments.length} | Vehicles in Transit: ${vehicles.filter(v => v.status === 'In Transit').length} | Road Blockages: ${roads.filter(r => r.status === 'Blocked').length} | Active Incidents: ${incidents.filter(i => i.status === 'Active' || i.status === 'Verified').length}`;
  doc.text(summaryText, 18, y + 15);
  doc.text(`Critical Risk Shipments requiring attention: ${shipments.filter(s => s.riskLevel === 'Critical').length}`, 18, y + 21);

  y += 34;

  // Table 1: Critical & Active Shipments
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('1. CRITICAL & IN-TRANSIT SHIPMENTS', 14, y);
  y += 6;

  // Header row
  doc.setFillColor(8, 127, 140);
  doc.rect(14, y, 182, 7, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.text('Tracking Code', 16, y + 5);
  doc.text('Commodity / Description', 50, y + 5);
  doc.text('Origin -> Destination', 115, y + 5);
  doc.text('ETA', 160, y + 5);
  doc.text('Risk', 185, y + 5);
  y += 7;

  doc.setTextColor(30, 41, 59);
  shipments.forEach(s => {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
    doc.setFont('helvetica', 'bold');
    doc.text(s.trackingCode, 16, y + 5);
    doc.setFont('helvetica', 'normal');
    doc.text(s.title.substring(0, 32), 50, y + 5);
    doc.text(`${s.origin.name.split(',')[0]} -> ${s.destination.name.split(',')[0]}`, 115, y + 5);
    doc.text(new Date(s.currentEta).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }), 160, y + 5);
    doc.text(s.riskLevel, 185, y + 5);
    y += 7;
    doc.setDrawColor(241, 245, 247);
    doc.line(14, y, 196, y);
  });

  y += 12;

  // Table 2: Active Road Disruption Status
  if (y > 240) {
    doc.addPage();
    y = 20;
  }
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('2. ROAD ACCESSIBILITY & DISRUPTIONS', 14, y);
  y += 6;

  doc.setFillColor(8, 127, 140);
  doc.rect(14, y, 182, 7, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.text('Corridor Name', 16, y + 5);
  doc.text('State / District', 75, y + 5);
  doc.text('Status', 135, y + 5);
  doc.text('Cause of Disruption', 160, y + 5);
  y += 7;

  doc.setTextColor(30, 41, 59);
  roads.forEach(r => {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
    doc.setFont('helvetica', 'bold');
    doc.text(r.roadName, 16, y + 5);
    doc.setFont('helvetica', 'normal');
    doc.text(`${r.state} (${r.district})`, 75, y + 5);
    doc.text(r.status, 135, y + 5);
    doc.text((r.causeOfDisruption || 'Operational').substring(0, 25), 160, y + 5);
    y += 7;
    doc.setDrawColor(241, 245, 247);
    doc.line(14, y, 196, y);
  });

  // Footer on all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(`PRAVAHA Operational Intelligence Platform - Page ${i} of ${totalPages}`, 14, 287);
    doc.text(`CONFIDENTIAL - FOR AUTHORIZED OFFICERS ONLY`, 125, 287);
  }

  doc.save(`${reportTitle.toLowerCase().replace(/\s+/g, '_')}_${Date.now()}.pdf`);
}
